// Common icons used across the application
export {
  // Navigation & UI
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  Plus,
  Search,
  Filter,
  Settings,
  MoreVertical,
  
  // Files & Documents
  FileText,
  Upload,
  Download,
  Share2,
  Edit,
  Trash2,
  Eye,
  Copy,
  Save,
  RefreshCw,
  
  // Status & Actions
  CheckCircle,
  AlertCircle,
  Clock,
  Star,
  Award,
  Target,
  Zap,
  
  // Business & Analytics
  DollarSign,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  LineChart,
  Activity,
  Users,
  Building2,
  Building,
  Globe,
  
  // Communication
  MessageSquare,
  Bell,
  Bot,
  Brain,
  Sparkles,
  Wand2,
  
  // Time & Calendar
  Calendar,
  Clock as ClockIcon,
  
  // Security & Access
  Lock,
  Unlock,
  Shield,
  
  // Media & Content
  Image,
  Video,
  Presentation,
  FileSpreadsheet,
  
  // Organization
  Archive,
  Bookmark,
  Tag,
  Folder,
  FolderOpen,
  
  // User & Profile
  User,
  LogOut,
  
  // Education & Learning
  GraduationCap,
  Lightbulb,
  Trophy,
  
  // Finance & Payments
  CreditCard,
  ReceiptText,
  
  // Technology & Development
  Rocket,
  Network,
  LifeBuoy,
  ExternalLink,
  
  // Workflow & Process
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Handshake,
  Briefcase,
  
  // Data & Information
  Info,
  XCircle,
  CheckCircle as CheckCircleIcon,
  
  // Network & Connectivity
  Wifi,
  WifiOff,
  Smartphone,
  
  // Design & Layout
  Layout,
  Layers,
  PenTool,
  Maximize,
  ArrowRightLeft,
  
  // AI & Intelligence
  Brain as BrainIcon,
  Sparkles as SparklesIcon,
  Wand2 as Wand2Icon,
  Bot as BotIcon,
  
  // Business Operations
  Building2 as Building2Icon,
  Handshake as HandshakeIcon,
  Briefcase as BriefcaseIcon,
  GraduationCap as GraduationCapIcon,
  
  // Analytics & Metrics
  BarChart3 as BarChart3Icon,
  PieChart as PieChartIcon,
  LineChart as LineChartIcon,
  Activity as ActivityIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  
  // User Interface
  Users as UsersIcon,
  Target as TargetIcon,
  DollarSign as DollarSignIcon,
  Calendar as CalendarIcon,
  Clock as ClockIcon2,
  Bell as BellIcon,
  MessageSquare as MessageSquareIcon,
  Zap as ZapIcon,
  Award as AwardIcon,
  Star as StarIcon,
  CheckCircle as CheckCircleIcon2,
  AlertCircle as AlertCircleIcon,
  Eye as EyeIcon,
  Edit as EditIcon,
  Trash2 as Trash2Icon,
  Download as DownloadIcon,
  Share2 as Share2Icon,
  Copy as CopyIcon,
  RefreshCw as RefreshCwIcon,
  Settings as SettingsIcon,
  MoreVertical as MoreVerticalIcon,
  Plus as PlusIcon,
  Search as SearchIcon,
  Filter as FilterIcon,
  Menu as MenuIcon,
  X as XIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  Globe as GlobeIcon,
  Building as BuildingIcon,
  User as UserIcon,
  LogOut as LogOutIcon,
  Sparkles as SparklesIcon2,
  Bot as BotIcon2,
  Brain as BrainIcon2,
  Wand2 as Wand2Icon2,
  Rocket as RocketIcon,
  Lightbulb as LightbulbIcon,
  Trophy as TrophyIcon,
  CreditCard as CreditCardIcon,
  ReceiptText as ReceiptTextIcon,
  Network as NetworkIcon,
  LifeBuoy as LifeBuoyIcon,
  ExternalLink as ExternalLinkIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  Handshake as HandshakeIcon2,
  Briefcase as BriefcaseIcon2,
  Info as InfoIcon,
  XCircle as XCircleIcon,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon,
  Smartphone as SmartphoneIcon,
  Layout as LayoutIcon,
  Layers as LayersIcon,
  PenTool as PenToolIcon,
  Maximize as MaximizeIcon,
  ArrowRightLeft as ArrowRightLeftIcon,
  FileText as FileTextIcon,
  Upload as UploadIcon,
  Download as DownloadIcon2,
  Share2 as Share2Icon2,
  Edit as EditIcon2,
  Trash2 as Trash2Icon2,
  Eye as EyeIcon2,
  Copy as CopyIcon2,
  Save as SaveIcon,
  RefreshCw as RefreshCwIcon2,
  Clock as ClockIcon3,
  CheckCircle as CheckCircleIcon3,
  AlertCircle as AlertCircleIcon2,
  Star as StarIcon2,
  Award as AwardIcon2,
  Target as TargetIcon2,
  Zap as ZapIcon2,
  MessageSquare as MessageSquareIcon2,
  Bell as BellIcon2,
  Bot as BotIcon3,
  Brain as BrainIcon3,
  Sparkles as SparklesIcon3,
  Wand2 as Wand2Icon3,
  Calendar as CalendarIcon2,
  Globe as GlobeIcon2,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Image as ImageIcon,
  Video as VideoIcon,
  Presentation as PresentationIcon,
  FileSpreadsheet as FileSpreadsheetIcon,
  Archive as ArchiveIcon,
  Bookmark as BookmarkIcon,
  Tag as TagIcon,
  Folder as FolderIcon,
  FolderOpen as FolderOpenIcon,
  User as UserIcon2,
  LogOut as LogOutIcon2,
  GraduationCap as GraduationCapIcon2,
  Lightbulb as LightbulbIcon2,
  Trophy as TrophyIcon2,
  CreditCard as CreditCardIcon2,
  ReceiptText as ReceiptTextIcon2,
  Rocket as RocketIcon2,
  Network as NetworkIcon2,
  LifeBuoy as LifeBuoyIcon2,
  ExternalLink as ExternalLinkIcon2,
  ArrowRight as ArrowRightIcon2,
  ArrowUp as ArrowUpIcon2,
  ArrowDown as ArrowDownIcon2,
  Handshake as HandshakeIcon3,
  Briefcase as BriefcaseIcon3,
  Info as InfoIcon2,
  XCircle as XCircleIcon2,
  Wifi as WifiIcon2,
  WifiOff as WifiOffIcon2,
  Smartphone as SmartphoneIcon2,
  Layout as LayoutIcon2,
  Layers as LayersIcon2,
  PenTool as PenToolIcon2,
  Maximize as MaximizeIcon2,
  ArrowRightLeft as ArrowRightLeftIcon2
} from 'lucide-react';
