import React from 'react';
import { DocumentTypeDefinition, DocumentTemplate, AIConfiguration, WorkflowTemplate } from '../document.types';
import { InfographicDocument, createInfographicDocument, validateInfographicDocument } from './InfographicDocument';
import { InfographicDocumentEditor } from '../../components/infographic/InfographicDocumentEditor';
import { InfographicDocumentRenderer } from '../../components/infographic/InfographicDocumentRenderer';
import { BarChart3 } from 'lucide-react';

// Infographic document templates
const infographicTemplates: DocumentTemplate[] = [
  {
    id: 'revenue-trends',
    name: 'Revenue Growth Trends',
    description: 'Track revenue growth over time with trend analysis and forecasting',
    type: 'infographic',
    content: {
      format: 'json',
      data: {
        infographic: {
          id: 'revenue-trends-template',
          title: 'Revenue Growth Trends',
          description: 'Track revenue growth over time with trend analysis',
          type: 'line',
          data: [
            { period: 'Q1 2023', revenue: 120000, target: 100000, growth: 20 },
            { period: 'Q2 2023', revenue: 135000, target: 120000, growth: 12.5 },
            { period: 'Q3 2023', revenue: 150000, target: 140000, growth: 11.1 },
            { period: 'Q4 2023', revenue: 175000, target: 160000, growth: 16.7 }
          ],
          config: {
            theme: 'corporate',
            layout: 'vertical',
            colors: ['#3b82f6', '#10b981', '#f59e0b'],
            showLegend: true,
            showGrid: true,
            showTooltips: true,
            enableAnimations: true,
            title: 'Revenue Growth Trends',
            subtitle: 'Quarterly Performance Analysis',
            footer: 'Generated by AI Document System'
          },
          metadata: {
            source: 'template',
            generatedAt: new Date(),
            aiConfidence: 0.9,
            version: '1.0.0',
            userId: '',
            category: 'financial',
            tags: ['revenue', 'growth', 'trends'],
            usage: { views: 0, exports: 0, shares: 0 }
          }
        }
      }
    },
    metadata: {
      category: 'infographic',
      tags: ['revenue', 'growth', 'financial'],
      status: 'draft',
      visibility: 'public',
      language: 'en',
      wordCount: 0,
      pageCount: 1,
      readingTime: 1,
      complexity: 'low',
      creationMethod: 'manual'
    },
    isPublic: true,
    createdBy: 'system',
    createdAt: new Date(),
    usageCount: 0,
    rating: 4.5
  },
  {
    id: 'market-share',
    name: 'Market Share Analysis',
    description: 'Visualize market share distribution with competitive positioning',
    type: 'infographic',
    content: {
      format: 'json',
      data: {
        infographic: {
          id: 'market-share-template',
          title: 'Market Share Analysis',
          description: 'Visualize market share distribution with competitive positioning',
          type: 'pie',
          data: [
            { company: 'Our Company', marketShare: 35, revenue: 2500000, growth: 15 },
            { company: 'Competitor A', marketShare: 25, revenue: 1800000, growth: 8 },
            { company: 'Competitor B', marketShare: 20, revenue: 1400000, growth: 5 },
            { company: 'Others', marketShare: 20, revenue: 1000000, growth: 2 }
          ],
          config: {
            theme: 'corporate',
            layout: 'grid',
            colors: ['#3b82f6', '#10b981', '#f59e0b', '#ef4444'],
            showLegend: true,
            showTooltips: true,
            enableAnimations: true,
            title: 'Market Share Analysis',
            subtitle: 'Competitive Landscape Overview',
            footer: 'Generated by AI Document System'
          },
          metadata: {
            source: 'template',
            generatedAt: new Date(),
            aiConfidence: 0.9,
            version: '1.0.0',
            userId: '',
            category: 'business',
            tags: ['market', 'share', 'competition'],
            usage: { views: 0, exports: 0, shares: 0 }
          }
        }
      }
    },
    metadata: {
      category: 'infographic',
      tags: ['market', 'share', 'business'],
      status: 'draft',
      visibility: 'public',
      language: 'en',
      wordCount: 0,
      pageCount: 1,
      readingTime: 1,
      complexity: 'low',
      creationMethod: 'manual'
    },
    isPublic: true,
    createdBy: 'system',
    createdAt: new Date(),
    usageCount: 0,
    rating: 4.3
  },
  {
    id: 'customer-segmentation',
    name: 'Customer Segmentation',
    description: 'Analyze customer demographics and behavior patterns',
    type: 'infographic',
    content: {
      format: 'json',
      data: {
        infographic: {
          id: 'customer-segmentation-template',
          title: 'Customer Segmentation',
          description: 'Analyze customer demographics and behavior patterns',
          type: 'scatter',
          data: [
            { segment: 'Enterprise', value: 50000, frequency: 12, satisfaction: 4.5 },
            { segment: 'SMB', value: 15000, frequency: 24, satisfaction: 4.2 },
            { segment: 'Startup', value: 5000, frequency: 36, satisfaction: 4.0 },
            { segment: 'Individual', value: 1000, frequency: 48, satisfaction: 3.8 }
          ],
          config: {
            theme: 'creative',
            layout: 'grid',
            colors: ['#8b5cf6', '#06b6d4', '#10b981', '#f59e0b'],
            showLegend: true,
            showTooltips: true,
            enableAnimations: true,
            title: 'Customer Segmentation',
            subtitle: 'Demographics and Behavior Analysis',
            footer: 'Generated by AI Document System'
          },
          metadata: {
            source: 'template',
            generatedAt: new Date(),
            aiConfidence: 0.9,
            version: '1.0.0',
            userId: '',
            category: 'marketing',
            tags: ['customer', 'segmentation', 'demographics'],
            usage: { views: 0, exports: 0, shares: 0 }
          }
        }
      }
    },
    metadata: {
      category: 'infographic',
      tags: ['customer', 'segmentation', 'marketing'],
      status: 'draft',
      visibility: 'public',
      language: 'en',
      wordCount: 0,
      pageCount: 1,
      readingTime: 1,
      complexity: 'medium',
      creationMethod: 'manual'
    },
    isPublic: true,
    createdBy: 'system',
    createdAt: new Date(),
    usageCount: 0,
    rating: 4.7
  }
];

// AI Configuration for infographics
const aiConfig: AIConfiguration = {
  enabled: true,
  autoAnalyze: true,
  autoSuggest: true,
  qualityThreshold: 80,
  customPrompts: {
    generate: 'Create a professional infographic that clearly visualizes the provided data with appropriate chart types, colors, and layout.',
    enhance: 'Improve this infographic by enhancing visual appeal, data clarity, and overall design quality.',
    analyze: 'Analyze this infographic for data accuracy, visual effectiveness, and design best practices.'
  },
  analysisDepth: 'comprehensive'
};

// Workflow templates for infographics
const workflowTemplates: WorkflowTemplate[] = [
  {
    id: 'infographic-review',
    name: 'Infographic Review Process',
    description: 'Standard review process for infographic documents',
    steps: [
      {
        id: 'data-validation',
        name: 'Data Validation',
        type: 'ai-analysis',
        assigneeRole: 'ai-assistant',
        dueDateOffset: 0,
        required: true,
        parallel: false
      },
      {
        id: 'design-review',
        name: 'Design Review',
        type: 'review',
        assigneeRole: 'designer',
        dueDateOffset: 1,
        required: true,
        parallel: false
      },
      {
        id: 'content-approval',
        name: 'Content Approval',
        type: 'approval',
        assigneeRole: 'manager',
        dueDateOffset: 2,
        required: true,
        parallel: false
      }
    ],
    isPublic: true,
    createdBy: 'system',
    createdAt: new Date()
  }
];

// JSON Schema for infographic documents
const infographicSchema = {
  type: 'object',
  properties: {
    id: { type: 'string' },
    type: { type: 'string', enum: ['infographic'] },
    title: { type: 'string' },
    description: { type: 'string' },
    content: {
      type: 'object',
      properties: {
        format: { type: 'string', enum: ['json'] },
        data: {
          type: 'object',
          properties: {
            infographic: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                title: { type: 'string' },
                description: { type: 'string' },
                type: { 
                  type: 'string', 
                  enum: ['bar', 'line', 'pie', 'area', 'scatter', 'radar', 'funnel', 'sankey', 'treemap', 'heatmap', 'gauge', 'waterfall'] 
                },
                data: { type: 'array' },
                config: { type: 'object' },
                metadata: { type: 'object' }
              },
              required: ['id', 'title', 'type', 'data', 'config', 'metadata']
            }
          },
          required: ['infographic']
        }
      },
      required: ['format', 'data']
    },
    metadata: {
      type: 'object',
      properties: {
        category: { type: 'string', enum: ['infographic'] },
        chartType: { type: 'string' },
        dataPoints: { type: 'number' },
        complexity: { type: 'string', enum: ['low', 'medium', 'high'] },
        aiGenerated: { type: 'boolean' },
        exportFormats: { type: 'array', items: { type: 'string' } }
      },
      required: ['category', 'chartType', 'dataPoints', 'complexity', 'aiGenerated', 'exportFormats']
    }
  },
  required: ['id', 'type', 'title', 'content', 'metadata']
};

// Infographic Document Type Definition
export const infographicDocumentType: DocumentTypeDefinition = {
  type: 'infographic',
  name: 'Infographic',
  description: 'AI-powered data visualization and infographic creation',
  icon: BarChart3,
  schema: infographicSchema,
  factory: (data: Partial<InfographicDocument>) => createInfographicDocument(data),
  validator: (document: InfographicDocument) => validateInfographicDocument(document),
  renderer: InfographicDocumentRenderer,
  editor: InfographicDocumentEditor,
  templates: infographicTemplates,
  aiConfig,
  workflowTemplates
};

export default infographicDocumentType;
